import type { AssistantSection, PortfolioKnowledgeItem } from "./types";

export const ASSISTANT_KNOWLEDGE_VERSION = "2026-04-17-semantic-v1";

export const PORTFOLIO_KNOWLEDGE: PortfolioKnowledgeItem[] = [
  {
    id: "overview",
    title: "Arihant overview",
    section: "about",
    category: "overview",
    aliases: ["who are you", "who is arihant", "about arihant", "introduce arihant", "overview", "background", "quick summary", "tell me about him"],
    keywords: ["product", "builder", "mba", "engineer", "salesforce", "usc", "cult", "technologist", "product manager", "technical product"],
    answerSentences: [
      "Arihant Rawat is a product-minded technologist with experience across startup and enterprise environments.",
      "He has built products at Cult.fit and Salesforce, and he is now pursuing an MBA at USC Marshall to deepen the product, business, and leadership side of his work.",
      "The portfolio is designed to show that blend of engineering depth, product thinking, and execution.",
    ],
    cta: { label: "Jump to About", href: "#about" },
    prompts: ["What did Arihant do at Salesforce?", "What projects has Arihant built?", "Why is he pursuing an MBA?"],
    priority: 3,
  },
  {
    id: "experience-overview",
    title: "Experience overview",
    section: "experience",
    category: "experience",
    aliases: ["experience", "work history", "career", "what has he done", "professional background"],
    keywords: ["salesforce", "cult", "product", "engineering", "leadership", "enterprise", "startup"],
    answerSentences: [
      "Arihant's experience spans both enterprise scale and startup-style execution.",
      "At Salesforce, he worked on Industries Cloud and Context Service across backend APIs, frontend work, and system design.",
      "At Cult.fit, he helped build core app experiences, collaborated closely with product and data teams, and eventually led app development across multiple products.",
      "That mix is a big part of why his profile reads as both technical and product-oriented.",
    ],
    cta: { label: "See Experience", href: "#experience" },
    prompts: ["What did Arihant do at Salesforce?", "How did Cult.fit shape his background?", "What kind of roles has he had?"],
    priority: 3,
  },
  {
    id: "salesforce",
    title: "Salesforce",
    section: "experience",
    category: "experience",
    aliases: ["salesforce", "context service", "industries cloud"],
    keywords: ["enterprise", "api", "frontend", "backend", "system design", "data cloud", "ai"],
    answerSentences: [
      "At Salesforce, Arihant worked on the Industries Cloud team on a product called Context Service.",
      "His work covered backend APIs, frontend development, and system design, and he also partnered with the Data Cloud team as the product gained traction internally and evolved into a paid offering.",
      "He mentored junior engineers, gave demos, and became one of the people pushing early agentic AI experimentation and tools like Cursor inside the team.",
    ],
    cta: { label: "See Experience", href: "#experience" },
    prompts: ["What did he do at Cult.fit?", "What projects show similar product thinking?", "What are his strongest skills?"],
    featured: true,
    priority: 4,
  },
  {
    id: "cultfit",
    title: "Cult.fit",
    section: "experience",
    category: "experience",
    aliases: ["cult", "cultfit", "cult.fit", "fitness startup", "app lead"],
    keywords: ["flutter", "mobile", "product", "startup", "architecture", "experiments", "data"],
    answerSentences: [
      "At Cult.fit, Arihant started as an app developer and became a senior product developer in a fast-moving startup environment.",
      "He worked deeply on the Flutter migration, helped shape the app architecture, and collaborated with product and data science teams on funnels, experimentation, and digital health products.",
      "Over time he became the app lead for the digital verticals team, owning architecture and helping ship multiple products from scratch.",
    ],
    cta: { label: "See Experience", href: "#experience" },
    prompts: ["What did Arihant do at Salesforce?", "What skills come through most strongly?", "What projects are most product-focused?"],
    featured: true,
    priority: 4,
  },
  {
    id: "skills-overview",
    title: "Skills overview",
    section: "skills",
    category: "skills",
    aliases: ["skills", "tech stack", "what tools", "what does he know", "strengths", "pm skills", "product manager skills", "technical skills"],
    keywords: ["typescript", "python", "react", "next", "flutter", "java", "llm", "ai", "product", "leadership", "strategy"],
    answerSentences: [
      "Arihant's skill set sits at the intersection of product development, full stack software, AI prototyping, and app development.",
      "On the technical side, the site highlights TypeScript, Python, Java, React, Next.js, Flutter, REST APIs, NLP, and analytics-oriented work.",
      "On the product side, the stronger pattern is that he likes taking ambiguous ideas and turning them into usable products with clear user value.",
    ],
    cta: { label: "See Skills", href: "#skills" },
    prompts: ["What are his strongest product skills?", "Which tools does he use most?", "What projects show those skills best?"],
    priority: 3,
  },
  {
    id: "education",
    title: "Education",
    section: "education",
    category: "education",
    aliases: ["education", "usc", "mba", "nsit", "nsut", "school", "college"],
    keywords: ["usc marshall", "mba", "engineering", "scholarship", "information technology"],
    answerSentences: [
      "Arihant is currently pursuing an MBA at USC Marshall, where the story becomes more explicitly about product, technology, and leadership.",
      "Before that, he studied Information Technology at NSIT, now NSUT, in Delhi and graduated with distinction.",
      "The portfolio also calls out major scholarships at USC, which helps explain why this chapter is a meaningful part of the overall story.",
    ],
    cta: { label: "See Education", href: "#education" },
    prompts: ["Why is Arihant pursuing an MBA?", "What is his professional background?", "How can I contact Arihant?"],
    priority: 3,
  },
  {
    id: "mba-why",
    title: "Why MBA",
    section: "education",
    category: "education",
    aliases: ["why mba", "why usc", "what is he doing now", "why business school", "current focus"],
    keywords: ["usc", "leadership", "product", "business", "technology"],
    answerSentences: [
      "Right now Arihant is at USC Marshall pursuing an MBA because it fits the broader arc of combining product thinking, technology, and business judgment.",
      "The move makes sense in the context of his background, since he already has strong engineering depth and hands-on product building experience.",
      "The MBA layer rounds out the leadership and decision-making side of the profile rather than replacing the technical side of it.",
    ],
    cta: { label: "See Education", href: "#education" },
    prompts: ["What did he do at Salesforce?", "What projects best show his product thinking?", "What is Arihant's background?"],
    priority: 4,
  },
  {
    id: "projects-overview",
    title: "Projects overview",
    section: "projects",
    category: "project",
    aliases: ["project", "projects", "portfolio work", "what has he built", "builder work", "best projects", "top projects", "case studies"],
    keywords: ["expertmind", "offgrid", "knowledge graph pro", "venue intelligence", "ipad", "video captioning", "product case study", "ai workflow"],
    answerSentences: [
      "Arihant's projects cover knowledge systems, consumer product ideas, AI workflows, and interactive portfolio design.",
      "A few of the strongest examples are ExpertMind and Knowledge Graph Pro on organizational memory, OffGrid on taste-based travel discovery, and Venue Intelligence Discovery on multi-agent expansion research.",
      "The project section is useful because it shows not just technical range, but how he frames and packages ideas as products.",
    ],
    cta: { label: "Open Projects", href: "#projects" },
    prompts: ["Tell me about OffGrid.", "What is ExpertMind?", "Which project is the most product-focused?"],
    priority: 3,
  },
  {
    id: "expertmind",
    title: "ExpertMind",
    section: "projects",
    category: "project",
    aliases: ["expertmind", "knowledge capture", "team memory", "expert knowledge", "knowledge risk"],
    keywords: ["knowledge", "expertise", "ai interviewer", "risk", "documentation", "memory", "organizational memory"],
    answerSentences: [
      "ExpertMind is a knowledge capture concept built around a very practical problem: teams lose critical context when experts leave or become bottlenecks.",
      "The product centers on knowledge-risk visibility and AI-assisted interviews so important expertise can be surfaced and reused instead of staying trapped in one person's head.",
      "It stands out because it feels less like a generic AI demo and more like a focused product concept with a real organizational pain point behind it.",
    ],
    cta: { label: "Open ExpertMind Repo", href: "https://github.com/ArihantRawat/ExpertMind" },
    prompts: ["How is Knowledge Graph Pro different?", "What other projects are product-oriented?", "Open the projects section."],
    featured: true,
    priority: 4,
  },
  {
    id: "knowledge-graph-pro",
    title: "Knowledge Graph Pro",
    section: "projects",
    category: "project",
    aliases: ["knowledge graph pro", "graph workspace", "organizational memory graph", "integration graph"],
    keywords: ["slack", "jira", "notion", "github", "zoom", "figma", "integrations", "graph", "organizational context"],
    answerSentences: [
      "Knowledge Graph Pro tackles the systems side of organizational memory by pulling work signals from tools like Slack, Jira, GitHub, and Notion into one graph-style workspace.",
      "The stronger idea is that fragmented activity becomes easier to explore and reuse when integrations, filtering, and persistence are designed into the product from the start.",
      "Together with ExpertMind, it shows a repeatable pattern in Arihant's project work around knowledge flow and shared context.",
    ],
    cta: { label: "Open Knowledge Graph Pro Repo", href: "https://github.com/ArihantRawat/knowledge-graph-pro" },
    prompts: ["How is it different from ExpertMind?", "What projects are consumer-facing?", "Which project feels most system-oriented?"],
    featured: true,
    priority: 4,
  },
  {
    id: "offgrid",
    title: "OffGrid",
    section: "projects",
    category: "project",
    aliases: ["offgrid", "travel app", "travel discovery", "vibe travel", "consumer travel"],
    keywords: ["travel", "consumer", "mobile", "flutter", "taste", "vibe", "recommendation", "brand", "storytelling"],
    answerSentences: [
      "OffGrid is a consumer-facing travel concept built around taste, vibe, and personal preference rather than generic top-10 recommendations.",
      "It pairs a mobile-first discovery flow with a stronger brand and storytelling layer, so the idea feels like a product experience rather than just a feature list.",
      "If you want the clearest example of Arihant's product sensibility on the portfolio, OffGrid is one of the strongest places to look.",
    ],
    cta: { label: "Open OffGrid Repo", href: "https://github.com/ArihantRawat/OffGrid" },
    prompts: ["What other projects are product-oriented?", "How does OffGrid compare to ExpertMind?", "Show me the projects section."],
    featured: true,
    priority: 4,
  },
  {
    id: "venue-intelligence-discovery",
    title: "Venue Intelligence Discovery",
    section: "projects",
    category: "project",
    aliases: ["venue intelligence", "venue intelligence discovery", "tixr", "expansion analysis", "venue scoring"],
    keywords: ["multi-agent", "scoring", "venues", "research", "market", "ticketing", "workflow", "decision support"],
    answerSentences: [
      "Venue Intelligence Discovery is a multi-agent workflow built to compare venues, markets, and ticketing signals at scale.",
      "The project is geared toward expansion analysis, so the output is not just research but prioritized scoring that makes next-step decisions easier to compare.",
      "It shows a more orchestration-heavy side of Arihant's work than the consumer-facing or portfolio-design projects.",
    ],
    cta: { label: "Open Venue Intelligence Repo", href: "https://github.com/ArihantRawat/VenueIntelligenceDiscovery" },
    prompts: ["Which projects show AI workflow thinking?", "Tell me about ExpertMind.", "What projects has Arihant built?"],
    featured: true,
    priority: 4,
  },
  {
    id: "video-captioning",
    title: "Video Captioning",
    section: "projects",
    category: "project",
    aliases: ["video captioning", "captioning", "ml project", "seq2seq"],
    keywords: ["tensorflow", "opencv", "machine learning", "frames", "training", "inference"],
    answerSentences: [
      "Video Captioning is a machine learning project focused on translating short video clips into natural-language descriptions.",
      "It covers the full workflow from preprocessing and frame extraction to training and inference, so it reads more like an end-to-end ML pipeline than a one-off notebook experiment.",
    ],
    cta: { label: "Open Video Captioning Repo", href: "https://github.com/ArihantRawat/Video_Captioning" },
    prompts: ["What projects show more product thinking?", "Tell me about Venue Intelligence Discovery.", "What are Arihant's strongest technical skills?"],
    priority: 3,
  },
  {
    id: "ipad-portfolio",
    title: "iPad Portfolio Experience",
    section: "projects",
    category: "interactive",
    aliases: ["ipad", "ipad portfolio", "interactive portfolio", "another way", "playful portfolio"],
    keywords: ["portfolio", "interactive", "gesture", "motion", "next.js", "framer motion"],
    answerSentences: [
      "The iPad Portfolio Experience reimagines a personal site as a tactile tablet-style product with windows, a dock, and gesture-inspired transitions.",
      "It is useful because it shows Arihant thinking about storytelling and interaction design, not just engineering implementation.",
      "If you want the more playful version of the portfolio, that is the best link to open.",
    ],
    cta: {
      label: "Open iPad Portfolio",
      href: "https://arihantrawat.github.io/arihant-ipad-site/?utm_source=portfolio&utm_medium=avatar&utm_campaign=explore_another_way",
    },
    prompts: ["What projects best show interaction design?", "What has Arihant built?", "How can I contact Arihant?"],
    priority: 4,
  },
  {
    id: "resume",
    title: "Resume",
    section: "top",
    category: "resume",
    aliases: ["resume", "cv", "pdf", "formal resume"],
    keywords: ["resume", "cv", "pdf"],
    answerSentences: [
      "Yes, there is a resume linked right from the hero section.",
      "The site itself already tells the richer story, but the PDF is there if you want the more formal version.",
    ],
    cta: { label: "View Resume", href: "/resume/arihant-rawat-pm.pdf" },
    prompts: ["What is Arihant's background?", "How can I contact Arihant?", "What projects has Arihant built?"],
    priority: 4,
  },
  {
    id: "contact",
    title: "Contact",
    section: "contact",
    category: "contact",
    aliases: ["contact", "email", "linkedin", "reach", "phone", "connect"],
    keywords: ["email", "linkedin", "phone", "contact", "reach out"],
    answerSentences: [
      "You can reach Arihant through email, LinkedIn, or phone from the contact section of the site.",
      "For a professional introduction, LinkedIn or email is probably the cleanest first move.",
      "If you want, I can point you straight to the contact section.",
    ],
    cta: { label: "Go to Contact", href: "#contact" },
    prompts: ["What kind of work has Arihant done?", "What projects should I look at first?", "Is there a resume?"],
    priority: 4,
  },
];

export const DEFAULT_SUGGESTED_PROMPTS = [
  "What did Arihant do at Salesforce?",
  "What projects has Arihant built?",
  "Why is Arihant pursuing an MBA?",
];

export const SECTION_FALLBACK_ITEM: Record<AssistantSection, string> = {
  top: "overview",
  about: "overview",
  skills: "skills-overview",
  experience: "experience-overview",
  education: "education",
  projects: "projects-overview",
  contact: "contact",
};
